language: node_js
node_js:
  - "12"
#branches:
#  only:
#    - master
script:
  - echo "Deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  target_branch: master
  token:
    secure: $FIREBASE_TOKEN
